sonar.projectKey=ZN93_Final-Space
sonar.organization=zn93

sonar.projectName=Final Space
sonar.projectVersion=1.0

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

sonar.sourceEncoding=UTF-8

sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.java.libraries=backend/target/dependency/*.jar
sonar.java.test.libraries=backend/target/dependency/*.jar

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/target/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/.angular/**,\
  **/*.spec.ts,\
  **/environment*.ts

sonar.test.exclusions=\
  **/target/**,\
  **/node_modules/**,\
  **/dist/**


sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
