# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/finalspace
spring.datasource.username=finalspace
spring.datasource.password=finalspace

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=finalspace-secret-key-finalspace-secret-key
jwt.expiration=86400000

# ===============================
# SERVER
# ===============================
server.port=8080