spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
management.endpoint.health.probes.enabled=true
logging.level.com.finalspace.backend=INFO
